### PR TITLE
Added some jokes

### PR DESCRIPTION
**Pull request by penaxr**
I added some jokes in the /data/jokes.json file

### CODE REVIEW

**Comment by Jain-Sanchit** [comment]
@penaxr  only 1 PR will  be accepted in this category !

**Comment by penaxr** [comment]
Okay but I dont get what you mean by "In this category" ? thats the first PR i've done in the jokes.json. 

did not need to label it as spam tho..

**Comment by Jain-Sanchit** [comment]
@penaxr  I mean that adding a quote or a joke or first pr .
I marked it spam as Hacktoberfest is not just about making 4 PR and winning a tshirt . Now you should make a bigger contribution or look for something better . I have merged a PR by you in quotes file . Now you can't make more PR in this first time PR category.

**Comment by penaxr** [comment]
First of all, I dont even know what hacktoberfest is, secondly You never specified anywhere in your readme.md and In your missing contributing.md that We could PR only once, so I only wanted to help because thats what open source is about right?But still I dont get why you decided its spam since thats not even the definition of spam, its more invalid that spam, anyways next time follow the rules and and a contributing.md

**Comment by Jain-Sanchit** [comment]
Okay , I got it . I am removing the spam tag , actually recently I came across the issue with others, so I just took this action . If you are not one among them then I apologize.
Thanks for contributing.

**Pull request closed without merging**
